#Registrar un usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "augustoterrera",
    "email": "augustoterrera@gmail.com",
    "password": "adminroot",
    "name": "Augusto",
    "lastname": "Terrera"
}

###Login de usuario

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "augustoterrera",
    "password": "adminroot"
}

###Ruta protegida

GET http://localhost:3000/protected

###Cerrar Sesion

POST  http://localhost:3000/logout